"""empty message

Revision ID: 820044003fb9
Revises: 
Create Date: 2019-11-20 12:10:56.330523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820044003fb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subtopics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('topic', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.Column('subtopic', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['subtopic'], ['subtopics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('subtopics')
    op.drop_table('topics')
    op.drop_table('answers')
    # ### end Alembic commands ###
