"""empty message

Revision ID: edca94c8464f
Revises: a29bd41071df
Create Date: 2019-11-12 21:08:49.262644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edca94c8464f'
down_revision = 'a29bd41071df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.Column('subtopic', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['subtopic'], ['subtopics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
